#force redirect car notre base url est "/quiz" qui est exigé par githubPages

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[build]
  command = "npm run build-only"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false #Ne pas capturer les fichiers existants

# Configuration spécifique pour la fonction 'parser'
[functions]  
  external_node_modules = ["jsdom"]